apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
