package com.ecommerce.apigateway.security;

import com.ecommerce.apigateway.dto.LoginRequest;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.reactive.server.WebTestClient;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc
@ActiveProfiles("test")
class JwtAuthenticationTest {

    @Autowired
    private WebTestClient webTestClient;

    @Autowired
    private JwtTokenProvider tokenProvider;

    @Test
    void login_ValidCredentials_ReturnsToken() {
        LoginRequest request = new LoginRequest();
        request.setUsername("customer1");
        request.setPassword("pass123");

        webTestClient.post()
                .uri("/auth/login")
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(request)
                .exchange()
                .expectStatus().isOk()
                .expectBody()
                .jsonPath("$.token").exists()
                .jsonPath("$.username").isEqualTo("customer1")
                .jsonPath("$.expiresIn").isEqualTo(86400);
    }

    @Test
    void login_InvalidCredentials_ReturnsUnauthorized() {
        LoginRequest request = new LoginRequest();
        request.setUsername("customer1");
        request.setPassword("wrongpass");

        webTestClient.post()
                .uri("/auth/login")
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(request)
                .exchange()
                .expectStatus().isUnauthorized();
    }

    /**
     * Validates that a token generated by JwtTokenProvider is valid and contains
     * the correct username. Tests token generation + validation directly without
     * requiring a live downstream service.
     */
    @Test
    void generateToken_WithValidUser_TokenIsValidAndParseable() {
        String token = tokenProvider.generateToken(
                "customer1",
                java.util.Arrays.asList("ROLE_USER")
        );

        assertNotNull(token, "Generated token should not be null");
        assertTrue(tokenProvider.validateToken(token), "Generated token should be valid");
        // Use assertEquals instead of assertTrue with equals() - fixes S5785
        assertEquals("customer1", tokenProvider.getUsernameFromToken(token),
                "Token should contain correct username");
    }

    @Test
    void accessProtectedEndpoint_WithoutToken_ReturnsUnauthorized() {
        webTestClient.get()
                .uri("/api/orders")
                .exchange()
                .expectStatus().isUnauthorized();
    }

    @Test
    void accessProtectedEndpoint_WithInvalidToken_ReturnsUnauthorized() {
        webTestClient.get()
                .uri("/api/orders")
                .header("Authorization", "Bearer invalid-token")
                .exchange()
                .expectStatus().isUnauthorized();
    }

    @Test
    void accessPublicEndpoint_WithoutToken_Success() {
        LoginRequest request = new LoginRequest();
        request.setUsername("customer1");
        request.setPassword("pass123");

        webTestClient.post()
                .uri("/auth/login")
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(request)
                .exchange()
                .expectStatus().isOk();
    }
}
