global:
  imageRegistry: "hiteshkhade"
  imagePullSecrets: []

eurekaServer:
  image:
    repository: hiteshkhade/eureka-server
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8761
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

apiGateway:
  image:
    repository: hiteshkhade/api-gateway
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 8088
    targetPort: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

orderService:
  image:
    repository: hiteshkhade/order-service
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8081
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilization: 70
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

inventoryService:
  image:
    repository: hiteshkhade/inventory-service
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8083
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilization: 70
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

paymentService:
  image:
    repository: hiteshkhade/payment-service
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8084
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

shippingService:
  image:
    repository: hiteshkhade/shipping-service
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8085
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

notificationService:
  image:
    repository: hiteshkhade/notification-service
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8086
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

postgres:
  image:
    repository: postgres
    tag: "15-alpine"
  service:
    port: 5432
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
  auth:
    username: postgres
    password: postgres

kafka:
  image:
    repository: confluentinc/cp-kafka
    tag: "7.5.0"
  service:
    port: 9092

zookeeper:
  image:
    repository: confluentinc/cp-zookeeper
    tag: "7.5.0"
  service:
    port: 2181

jwtSecret: "changeme-use-k8s-secret-in-production"
